'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
export default function CustomerLogin(){
 const [signup,setSignup]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);const router=useRouter();
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch('/api/order/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,action:signup?'signup':'login'})});const data=await r.json();if(!r.ok)throw new Error(data.message);router.push('/order/menu');}catch(err){setError(err instanceof Error?err.message:'Unable to sign in');}finally{setBusy(false);}}
 const input='w-full bg-charcoal border border-gray-600 rounded-lg p-3 text-white mb-4';
 return <div className="min-h-screen bg-pitch-black py-24 px-4"><div className="max-w-md mx-auto bg-deep-space p-6 sm:p-8 rounded-2xl border border-charcoal"><h1 className="text-3xl text-premium-orange font-bold mb-3">{signup?'Create your account':'Welcome back'}</h1><p className="text-gray-300 mb-6">Save your details, or order as a guest.</p><form onSubmit={submit}>{signup&&<><label htmlFor="name">Name</label><input className={input} id="name" name="name" autoComplete="name" minLength={2} required/><label htmlFor="phone">Mobile number</label><input className={input} id="phone" name="phone" type="tel" pattern="[6-9][0-9]{9}" autoComplete="tel-national" required/></>}<label htmlFor="email">Email</label><input className={input} id="email" name="email" type="email" autoComplete="email" required/><label htmlFor="password">Password</label><input className={input} id="password" name="password" type="password" minLength={8} maxLength={128} autoComplete={signup?'new-password':'current-password'} required/>{error&&<p role="alert" className="text-red-300 mb-4">{error}</p>}<button disabled={busy} className="w-full bg-premium-orange text-black font-bold p-3 rounded-lg">{busy?'Please wait…':signup?'Create account':'Sign in'}</button></form><button className="w-full mt-5 text-golden-glow" onClick={()=>{setSignup(!signup);setError('');}}>{signup?'Already registered? Sign in':'New here? Create an account'}</button><Link href="/order/menu" className="block text-center border border-gray-500 rounded-lg p-3 mt-5">Continue as guest →</Link></div></div>;
}
