'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {useMenu} from '@/lib/useMenu';
import {readCart} from '@/lib/catalog';
import {type MenuItem} from '@/data/menu';
export default function MenuBrowser(){const items=useMenu().filter(i=>i.category!=='combo');const [category,setCategory]=useState('all'),[query,setQuery]=useState(''),[cartCount,setCartCount]=useState(0),[notice,setNotice]=useState('');useEffect(()=>{const c=new URLSearchParams(window.location.search).get('category');if(c&&['steamed','fried','kurkure'].includes(c))setCategory(c);setCartCount(readCart().length);},[]);
function add(item:MenuItem,quantity:number){const cart=readCart();cart.push({menuItem:{id:item.id,name:item.name,category:item.category,price5pc:item.halfPrice,price10pc:item.price,imageUrl:item.image,isVeg:true,isAvailable:true,description:item.description},quantity,spiceLevel:'medium',subtotal:quantity===5?item.halfPrice:item.price});sessionStorage.setItem('cart',JSON.stringify(cart));setCartCount(cart.length);setNotice(`${item.name} (${quantity} pieces) added to your cart.`);}
const shown=items.filter(i=>(category==='all'||category===i.category)&&i.name.toLowerCase().includes(query.toLowerCase()));return <div className="mm-wrap mm-page"><div className="mm-section-head"><div><p className="mm-eyebrow">STEAM, FRY, CRUNCH</p><h1>Find your <em>favourite.</em></h1><p className="mm-lead">Pick your filling and plate size. Send your order on WhatsApp for confirmation.</p></div><a className="mm-text-link" href="/images/outlet/menu-card.webp" target="_blank" rel="noopener noreferrer">View menu card ↗</a></div><div className="mm-menu-tools"><div className="mm-tabs" aria-label="Menu categories">{['all','steamed','fried','kurkure'].map(c=><button key={c} aria-pressed={c===category} className={c===category?'active':''} onClick={()=>setCategory(c)}>{c==='all'?'All momos':c}</button>)}</div><input aria-label="Search menu" type="search" placeholder="Search your favourite…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="mm-notice" role="status" aria-live="polite">{notice||'Half plate · 5 pieces     /     Full plate · 10 pieces'}</div><div className="mm-three mm-menu-grid">{shown.map(item=><article className="mm-food-card" key={item.id}><div className="mm-card-image"><img src={item.image} alt={item.name} loading="lazy"/><span><b className="mm-veg">●</b> {item.category.toUpperCase()}</span></div><div className="mm-card-copy"><h2>{item.name}</h2><p>{item.description}</p><div className="mm-portion-buttons"><button onClick={()=>add(item,5)} aria-label={`Add ${item.name}, 5 pieces`}>5 pcs <strong>₹{item.halfPrice}</strong><span>+</span></button><button onClick={()=>add(item,10)} aria-label={`Add ${item.name}, 10 pieces`}>10 pcs <strong>₹{item.price}</strong><span>+</span></button></div></div></article>)}</div>{!shown.length&&<div className="mm-empty"><h2>No momos found.</h2><p>Try a different filling or category.</p><button className="mm-btn" onClick={()=>{setQuery('');setCategory('all');}}>Reset filters</button></div>}<div className="mm-menu-bottom"><Link href="/combo-deals" className="mm-text-link">Ordering for a group? See combos ↗</Link></div>{cartCount>0&&<Link href="/order/cart" className="mm-cart-bar"><span>{cartCount} {cartCount===1?'plate':'plates'} in your cart</span><strong>View cart →</strong></Link>}</div>}
