import fs from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {request,chromium as pw} from '@playwright/test';
import chromium from '@sparticuz/chromium';
import assert from 'node:assert/strict';
const origin=process.env.VERIFY_URL||'http://localhost:35104';const file=await fs.open('/tmp/momo-extra-server.log','w');const server=process.env.VERIFY_URL?null:spawn(process.execPath,['node_modules/next/dist/bin/next','start','-p','35104','-H','127.0.0.1'],{stdio:['ignore',file.fd,file.fd]});let browser;const results=[];
async function test(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message);}}
try{for(let i=0;i<60;i++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,500));}
const env=Object.fromEntries((await fs.readFile('.env.local','utf8')).split('\n').filter(l=>l&&!l.startsWith('#')&&l.includes('=')).map(l=>{const i=l.indexOf('=');return [l.slice(0,i),l.slice(i+1).replace(/^"|"$/g,'')]}));const api=await request.newContext({baseURL:origin});assert.equal((await api.post('/api/auth/login',{data:{username:env.ADMIN_USERNAME,password:env.ADMIN_PASSWORD}})).status(),200);
for(const section of ['franchise','careers','legal-pages','translations','api-integrations','testimonials','page-builder','seo','performance'])await test('extra CMS '+section,async()=>{const r=await api.get('/api/cms/'+section+(section==='page-builder'?'?page=home':''));assert.ok(r.status()<400,await r.text());});
await test('media upload and image delivery',async()=>{const r=await api.post('/api/cms/media/upload',{multipart:{file:{name:'qa.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+k9T8AAAAASUVORK5CYII=','base64')}}});assert.equal(r.status(),200,await r.text());const d=await r.json();const response=await api.get(d.file.url);assert.equal(response.status(),200);assert.ok(response.headers()['content-type'].startsWith('image/'));await api.delete('/api/cms/media?id='+d.file.id);});
browser=await pw.launch({args:chromium.args.filter(a=>a!=='--single-process'),executablePath:await chromium.executablePath(),headless:true});const context=await browser.newContext({storageState:await api.storageState(),viewport:{width:1440,height:900}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const dirs=await fs.readdir('app/admin/dashboard',{withFileTypes:true});
for(const dir of dirs.filter(d=>d.isDirectory())){const path='/admin/dashboard/'+dir.name;await test('admin page '+dir.name,async()=>{const r=await page.goto(origin+path,{waitUntil:'networkidle'});assert.ok(r.status()<400);assert.ok(!page.url().includes('/admin/login'),'Auth redirect');assert.ok(!(await page.locator('body').innerText()).includes('Application error'));});}
await test('admin runtime errors',async()=>assert.deepEqual(errors,[]));await context.close();
const mobile=await browser.newContext({viewport:{width:390,height:844}});const p=await mobile.newPage();p.on('dialog',d=>d.dismiss());let whatsapp='';await p.route('https://wa.me/**',async r=>{whatsapp=r.request().url();await r.abort();});
await test('menu search',async()=>{await p.goto(origin+'/menu');await p.getByPlaceholder(/Search/).fill('Paneer');await p.waitForTimeout(600);assert.ok((await p.locator('body').innerText()).includes('Paneer'));});
await test('checkout WhatsApp details',async()=>{await p.goto(origin+'/order/menu',{waitUntil:'networkidle'});await p.getByRole('button',{name:'Add 10pc',exact:true}).first().click();await p.goto(origin+'/order/checkout');await p.locator('#checkout-name').fill('Order QA');await p.locator('#checkout-phone').fill('9876543210');await p.getByRole('button',{name:/Continue to WhatsApp/}).click();await p.waitForTimeout(1500);assert.ok(whatsapp.includes('919955955191'));assert.ok(decodeURIComponent(whatsapp).includes('Order QA'));assert.ok(decodeURIComponent(whatsapp).includes('10 pieces'));});
for(const [path,name] of [['/','home'],['/menu','menu'],['/catering','catering']]){await p.goto(origin+path,{waitUntil:'networkidle'});await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=500){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,80));}window.scrollTo(0,0);});await p.waitForTimeout(500);await p.screenshot({path:'artifacts/'+name+'-mobile.png',fullPage:true});}
await mobile.close();await api.dispose();
}finally{if(browser)await browser.close();if(server)server.kill();await file.close();await fs.writeFile('artifacts/extra-verification.json',JSON.stringify(results,null,2));}if(results.some(r=>!r.pass))process.exitCode=1;
